# Generated by Django 4.2.1 on 2023-06-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True)),
                ('content', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('national', 'National'), ('politics', 'Politics'), ('valley', 'Valley'), ('opinion', 'Opinion'), ('money', 'Money'), ('sports', 'Sports'), ('culture', 'Culture')], max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
