# Generated by Django 4.2.1 on 2023-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
