# Generated by Django 4.2.1 on 2023-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswebsite', '0002_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('national', 'National'), ('politics', 'Politics'), ('valley', 'Valley'), ('opinion', 'Opinion'), ('money', 'Money'), ('sports', 'Sports'), ('culture', 'Culture'), ('others', 'Others')], max_length=255),
        ),
    ]
